services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
    ports:
      - 9696:9696
    restart: unless-stopped

x-nexterm:
  name: Prowlarr
  version: latest
  description: Indexer manager/proxy built on the popular *arr .net/reactjs base stack
  icon: https://raw.githubusercontent.com/Brandon-Roff/Nexterm-Apps/main/logos/Prowlarr.png
  category: Media
  port: 9696