services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
      - ./tv:/tv
      - ./downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

x-nexterm:
  name: Sonarr
  version: latest
  description: Smart PVR for newsgroup and bittorrent users
  icon: https://raw.githubusercontent.com/gnmyt/Nexterm-AppStore/main/logos/Sonarr.png
  category: Media
  port: 8989